# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: FortifyDemo
  name: Default

steps:

- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: 'C:\agent\_work\5\a'
    FodConnection: 'FOD Demo'
    ReleaseOptions: '0'
    ReleaseId: 274581
    EntitlementSelection: '1'
    EntitlementPreference: '2'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'none'
    
- task: FortifyOnDemandDynamic@7
     inputs:
       APIUrl: 'https://api.ams.fortify.com'
       ReleaseId: '274581'
       APIAuthenticationType: '2'
       Username: 'hnematollahy1'
       PersonalAccessTokenSecret: 'RUZcbDlKU2swMFZ7UldYWlFzc0NGUjRrWzhBeWlv0'
       TenantID: 'franklinbank'
       EntitlementPreference: '1'